accounts/urls.py
from django.urls import path 

from blog.views import review_articles,accept_article,reject_article
from .views import (
						login_view, 
						register_view,
						dashboard_view, 
                        user_dashboard_edit,
						logout_view,
						kave_negar_token_send,
                        courses_view,
                        edit_course_view,
                        create_course_view,
                        
					)

app_name= 'accounts'
urlpatterns = [

	path('login/' , login_view , name = 'login_view'),

	path('dashboard/' , dashboard_view , name = 'dashboard_view'),
    
	path('dashboard/edit/', user_dashboard_edit, name='user_dashboard_edit'),
    
	path('dashboard/courses/' , courses_view , name = 'courses_view'),
    
    path('courses/<int:course_id>/', edit_course_view, name='edit_course_view'),
    
	path('courses/create/', create_course_view, name='create_course_view'),

	path('register/' , register_view , name = 'register_view'),

	path('logout/', logout_view, name='logout_view'),

	path('kave_negar_token_send/',kave_negar_token_send,name = 'kave_negar_token_send'),
    
]

blog/urls.py
from django.urls import path,include

from .views import home_view , blog_detail,AddarticleView,SearchView,about_us,contact_us


urlpatterns = [

    path('' , home_view , name = 'blog_home'),

    path('blogs/<id>/' , blog_detail , name = 'blog_detail'),

    path('search/' , SearchView , name = 'search'),

    path('addarticle/' , AddarticleView , name = 'addarticle'),  

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

    path('about/', about_us, name='about'),

    path('contact/', contact_us, name='contact'),

 







   # path('<id>/' , comment_create , name = 'comment_create')



]

config/urls.py
from django.contrib import admin

from django.urls import path , include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/' ,  include('accounts.urls')),

    path('' , include('blog.urls')),

    path("__reload__/", include("django_browser_reload.urls")),  # This is important!
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django_jalali.db import models as jmodels

from django.contrib.auth import get_user_model

from accounts.models import MyUser


class Course(models.Model):

    category = models.ForeignKey("Category" , null = True ,  blank = True , on_delete = models.SET_NULL)

    title = models.CharField(max_length = 250)

    content = models.TextField()

    image = models.ImageField(upload_to = 'blog/' , null = True , blank = True)

    slug = models.SlugField(unique = True , max_length = 250)

    status = models.BooleanField(default = False)

    time_of_study = models.IntegerField(default = 0)

    created_date = models.DateTimeField(auto_now_add = True)

    updated_date = models.DateTimeField(auto_now = True)

    created_date_jalali = jmodels.jDateField(auto_now_add = True , blank = True , null = True)

    updated_date_jalali = jmodels.jDateField(auto_now = True , blank = True , null = True)

    teacher = models.CharField(max_length = 150)

    price = models.IntegerField(null = True)

    discount_price = models.IntegerField(null=True, blank=True)  # قیمت با تخفیف (اختیاری)
    
    def get_final_price(self):
        """محاسبه قیمت نهایی با تخفیف (در صورت وجود)"""
        return self.discount_price if self.discount_price else self.price
    
    # Methods
    def __str__(self):

        return str(self.title)

class Category(models.Model):

    '''
        
        THIS IS A MODEL FOR CATEGORY OBJECTS...

    '''

    title = models.CharField(max_length = 250)

    slug = models.SlugField(unique = True , max_length = 250)

    created_date = models.DateTimeField(auto_now_add = True)

    updated_date = models.DateTimeField(auto_now = True)

    created_date_jalali = jmodels.jDateField(auto_now_add = True , blank = True , null = True)

    updated_date_jalali = jmodels.jDateField(auto_now = True , blank = True , null = True)

    # Methods
    def __str__(self):

        return f'{self.id} , {self.title}'

class Comment(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
    

class Article(models.Model):
    author =models.ForeignKey(MyUser,on_delete=models.PROTECT)
    category =models.ForeignKey(Category,on_delete=models.PROTECT)
    title=models.CharField(max_length=800)
    abstract= models.TextField(default=None)
    key_word_1=models.CharField(max_length=100,default=None)
    key_word_2=models.CharField(max_length=100,default=None)
    key_word_3=models.CharField(max_length=100,default=None)    
    body= models.TextField(default=None)
    image = models.ImageField(upload_to = 'blog/' , null = True , blank = True)
    created_date_jalali = jmodels.jDateField(auto_now_add = True , blank = True , null = True)

    STATUS_CHOICES={
        ('draft','Draft'),
        ('published','Published'),
        ('archived','Archived'),
    }
    status=models.CharField( max_length=20, choices=STATUS_CHOICES,default=None,null=True)
    def __str__(self):  
        return '{}'.format(self.title)


class Basket(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}"

class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE, related_name="items")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.basket.user.username} - {self.course.title}"

class Order(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20,
        choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده')],
        default='pending'
    )
    amount = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.course.title} - {self.status}"

blog/forms.py
from django import forms
from .models import Article
from django.forms import ModelForm

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['author', 'category', 'title', 'abstract', 'key_word_1', 'key_word_2', 'key_word_3', 'body', 'image', 'status']
        
    # Customizing widgets for better UI
    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''})
        self.fields['abstract'].widget = forms.Textarea(attrs={'class': 'form-control', 'placeholder': ''})
        self.fields['body'].widget = forms.Textarea(attrs={'class': 'form-control', 'placeholder': ''})
        self.fields['image'].widget = forms.ClearableFileInput(attrs={'class': 'form-control'})
        self.fields['status'].widget = forms.Select(choices=Article.STATUS_CHOICES, attrs={'class': 'form-control'})
        self.fields['author'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['category'].widget = forms.Select(attrs={'class': 'form-control'})

blog/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse

from .models import Course	

from .models import Comment,Article

from accounts.models import MyUser

from django.contrib import messages

from django.contrib.auth.decorators import login_required

# a view for home
def home_view(request):

    courses = Course.objects.filter(status=True)
    # posts = Post.objects.all()

    context = {
        'courses': courses,
    }

    return render(request, 'blog/blogs.html', context)

def SearchView(request):

    query = request.GET.get('search','')
    results = Course.objects.filter(name__iconcontaints=query) if query else []

    return render(request, 'blog/search_resualts.html',{'resualts': results , 'query': query})


def blog_detail(request, id):
    course = Course.objects.get(pk=id, status=True)
    comments = course.comments.filter(active=True)
    price = course.price
    if request.method == 'POST':
        comment_content = request.POST.get('comment_content')

        if not comment_content:
            messages.error(request, 'متن شما خالی است')
        else:
            try:
                comment = Comment.objects.get(
                    body=comment_content,
                    name=request.user.first_name,
                    email=request.user.email,
                    active=False,
                    course=course
                )

                messages.error(request, 'شما قبل این نظر را ارسال کردید')
            except Comment.DoesNotExist:
                comment = Comment.objects.create(
                    course=course,
                    name=request.user.first_name,
                    email=request.user.email,
                    body=comment_content,
                    active=False
                )
                messages.success(request, 'نظر شما ثبت شد')
                return redirect('.')
            
    

    return render(request, 'blog/blog-detail.html', {'course': course, 'comments': comments, 'price':price})




def AddarticleView(request):
    if request.method == 'POST':
		# article=Article(
		# 	user = request.POST['user'],
    	# 	category = request.POST['category'],
		# 	title = request.POST['title'],
		# 	abstract = request.POST['abstract'],
		# 	key_word_1=request.POST['key_word_1'],
		# 	key_word_2=request.POST['key_word_2'],
		# 	key_word_3=request.POST['key_word_3'],
		# 	body=request.POST['body'],
		# 	created_date_jalali=request.POST['created_date_jalali'],
		# )
            # 'user': request.POST.get('user'),
            # 'category': request.POST.get('category'),
            # 'title': request.POST.get('title'),
            # 'abstract': request.POST.get('abstract'),
            # 'key_word_1': request.POST.get('keywords1'),
            # 'key_word_2': request.POST.get('keywords2'),
            # 'key_word_3': request.POST.get('keywords3'),
            # 'body': request.POST.get('body'),
            # 'created_date_jalali': request.POST.get('date'),
        
        return render(request, 'registerations/addarticle.html')
    else:
        return render(request, 'registerations/addarticle.html')

@login_required
def review_articles(request):
    if request.user.is_superuser:
        articles= Article.objects.filter(status='draft')
        return render(request)
    else:
        return HttpResponse('what??bro you are normal user this page is for superuser')
        
@login_required
def accept_article(request,article_id):
    article=Article.objects.get(id=article_id)
    if request.user.is_superuser:
        article.status='published'
        article.save()
        messages.SUCCESS(request,f'accepted article{article.title}.')
    else:
        return HttpResponse('what??bro you are normal user this page is for superuser')

    return redirect('../')

@login_required
def reject_article(request,article_id):
    article=Article.objects.get(id=article_id)
    if request.user.is_superuser:
        article.status='archived'
        article.save()
        messages.SUCCESS(request,f'accepted article{article.title}.')
    else:
        return HttpResponse('what??bro you are normal user this page is for superuser')

    return redirect('../')  


def about_us(request):
    return render(request, 'blog/about-us.html')

def contact_us(request):
    return render(request, 'blog/contact-us.html')

templates/blog/about-us.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<!-- Image Header -->
<div class="text-center pt-1 w-full flex justify-center px-5 pb-3 mx-5">
    <div class="flex justify-center w-full px-5 mx-5">
        <div class="border-2 border-gray-300 p-4 px-5 rounded-lg flex justify-center ml-2">
            <img src="{% static 'blog/images/logo.png' %}" alt="About Us" class="w-50 h-40 object-fit">
        </div>
    </div>
</div>
<!-- end image header -->

<!-- About Us Section -->
<div class="py-1">
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                <div class="d-flex w-100 justify-content-start align-items-center" dir="rtl">
                    <h1>درباره ما</h1>
                </div>
            </div>
            <div class="col-12" style="border: radius 3px; border-right:3px solid green;">
                <div class="d-flex w-100 justify-content-center align-items-center" dir="rtl" style="text-align: justify; font-size: 14px; line-height: 25px; color: #828282;">
                    <p>
                        ما در اینجا جمع شده‌ایم تا بهترین خدمات و محصولات را به شما ارائه دهیم. تیم ما از افراد متخصص و با تجربه‌ای تشکیل شده است که هدفشان ایجاد تجربه‌ای عالی برای شماست. ما همواره در تلاشیم تا با نوآوری و خلاقیت، خدماتی متفاوت و به یادماندنی ارائه دهیم.
                    </p>
                    <p>
                        اعتماد شما برای ما سرمایه‌ای بزرگ است و سعی می‌کنیم با ارائه‌ی بهترین کیفیت، آن را حفظ کنیم. از اینکه ما را انتخاب کرده‌اید، سپاسگزاریم.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end About Us Section -->

{% endblock content %}

templates/blog/blog-detail.html
{% extends 'blog/base.html' %}

{% load static %}
{% load ratings %}

{% block content %}
<style>
/* General responsive styling for the image */
.responsive-image {
    max-width: 100%; /* Adjust size responsively */
    height: auto; /* Maintain aspect ratio */
    object-fit: contain;
    display: block; /* Ensures visibility */
    margin: 0 auto; /* Centers the image horizontally */
}

/* Container for proper centering */
.text-center {
    display: flex; /* Enables flexbox */
    justify-content: center; /* Centers content horizontally */
    align-items: center; /* Centers content vertically */
    padding: 20px; /* Optional spacing */
}

/* For smaller screens */
@media (max-width: 768px) {
    .text-center {
        padding: 10px; /* Adjust spacing for smaller screens */
    }

    .border-2 {
        border-width: 1px; /* Reduce border size for smaller devices */
    }
}
</style>

<!-- Image Header -->
<div class="border-2 border-gray-300 text-center p-4 mx-5 px-5 rounded-lg">
    <img src="{{ course.image.url }}" alt="IMAGE" class="responsive-image">
</div>


<!-- for title and general information of blog -->
<div class="py-1">
	<div class="container">
		<div class="row d-flex justify-content-center" dir="rtl">

			<div class="col-12 col-md-5 d-flex justify-content-center align-items-center mt-md-0 mt-3">

				<div class="d-flex w-100 flex-column justify-content-center align-items-center">
					<div class="d-flex justify-content-center align-items-center p-2 mb-2" style="border-radius:50%;background-color: #f1f1f1;">
						🧑‍🏫
					</div>
					<div dir="rtl" style="font-size:13px;">{{course.teacher}}</div>
				</div>

				<div class="d-flex w-100 flex-column justify-content-center align-items-center">
					<div class="d-flex justify-content-center align-items-center p-2 mb-2" style="border-radius:50%;background-color: #f1f1f1;">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
							<path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
							<path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z"/>
						</svg>
					</div>
					<div dir="rtl" style="font-size:13px;"> {{ comments.count }} نظر</div>
				</div>

				<div class="d-flex w-100 flex-column justify-content-center align-items-center">
					<div class="d-flex justify-content-center align-items-center p-2 mb-2" style="border-radius:50%;background-color: #f1f1f1;">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
							<path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
							<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
						</svg>
					</div>
					<div dir="rtl" style="font-size:13px;"> {{course.time_of_study}} دقیقه </div>
				</div>

			</div>
		</div>
	</div>
</div>
<!-- end for title and general information of blog -->


<!-- seccond section -->

<div class="py-3">
	<div class="container">
		<div class="row">
			<div class="col-12 mb-3">
				<div class="d-flex w-100 justify-content-start align-items-centers" dir="rtl">
					{{ course.title }}
				</div>
			</div>
			<div class="col-12" style="border: radius 3px;;border-right:3px solid green ;">
				<div class="d-flex w-100 justify-content-center align-items-centers" dir="rtl" style="text-align: justify;font-size: 14px;line-height: 25px;color: #828282;">
					{{course.content}}
				</div>
			</div>

		</div>
	</div>
</div>
<!-- end seccond section -->

<!-- 3rd section -->
<div class="py-5">
  <div class="container">
    <div class="row" dir="rtl">
      <div class="col-12 col-md-9">
        <h3 class="text-end fw-bold" style="color: #00d5b6; font-size: 1.75rem;">
          قیمت:
          <span style="color: #333;">{{ course.price }} تومان</span>
        </h3>

        <div class="">
          <input type="submit" class="btn btn-primary px-5" value="خرید">
        </div>
        <!-- my 6th form -->
        <div class="d-flex w-100 justify-content-center align-items-center flex-column mt-5">
          
          <!-- For reviews -->
          <div class="d-flex flex-row-reverse justify-content-between align-items-end w-100 mb-4">
            <div class="d-flex flex-column justify-content-center align-items-end" style="margin-left: 30%;">
              <h6>نظرات کاربران</h6>
              <div class="w-25" style="border: none; border: 2px solid #00d5b6; margin-left: 50%;"></div>
            </div>
          </div>

          <div class="d-flex w-100 flex-column justify-content-center align-items-center" dir="rtl">
            <div class="row w-100">
              <!-- Add your review content here if needed -->
            </div>
          </div>
        </div>

        <!-- End review -->

        <!-- Start send review -->
        <div class="d-flex flex-row-reverse justify-content-between align-items-end w-100 mb-4">
          <div class="d-flex flex-column justify-content-center align-items-end">
            
          </div>
        </div>
	

        {% for comment in comments %}
		<div dir="rtl" class="comments" style="padding: 15px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 7px; background-color: #f9f9f9; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
		<p class="font-weight-bold" style="margin-bottom: 5px;">
			{{ comment.name }}
			<span class="text-muted font-weight-normal" style="font-size: 0.9em;">{{ comment.created_on }}</span>
		</p>
		<div style="white-space: pre-line;">
			{{ comment.body | linebreaks }}
		</div>
		</div>
		{% endfor %}


    <!-- Send review form -->
		<h6 dir="rtl" >افزودن نظر</h6>
		<div class="w-25" style="border: none; border: 2px solid #00d5b6; text-align: right; margin-left: 60%"></div>
        {% if user.is_authenticated %}
        <form action="" method="POST" id="main_form"  class="comment_form">
          <div class="d-flex justify-content-center align-items-center">
            <div class="row w-100" dir="rtl">
              
              {% csrf_token %}

              <div class="col-12">
                <div>
                  <div class=" mb-1 mt-4" style="color: #828282; font-size: 14px;">متن پیام</div>
                  <textarea class="w-100" name="comment_content" cols="30" rows="10" style="border: 1px solid #ccc; border-radius: 7px;"></textarea>
                </div>
              </div>

              <div class="col-12 mt-4 d-flex justify-content-end">
                <div>
                  <input type="submit" class="btn btn-primary px-5" value="Post">
                </div>
              </div>
            </div>
          </div>
        </form>
        {% else %}
        <h2>ابتدا <a href="{% url 'accounts:login_view' %}" style="color: cyan;">وارد شوید</a></h2>
        {% endif %}

        

      </div>
    </div>
  </div>
</div>

<!-- end 3th section -->

{% endblock content %}

templates/blog/blogs.html
{% extends 'blog/base.html' %}

{% load static %}

{% load my_first_template_tag %}

{% block title %}تبریز{% endblock title %}

{% block content %}

  <!-- first section -->
  <div class="py-5">
    <div class="container" dir="rtl">
      <div class="row">

      {% for course in courses %}

          <!-- card -->
          <div class="col-md-6 col-lg-4 col-12 d-flex justify-content-center align-items-center mb-3">
            <div class="d-flex w-100 justify-content-center align-items-center bg-white flex-column" style="border: 1px solid #eee;border-radius: 10px;">
              <div class="position-relative w-100 d-flex justify-content-center align-items-center ">
                <a href="{% url 'blog_detail' course.id %}" class="w-100 d-flex justify-content-center align-items-center">
                  <img src="{{course.image.url}}" alt="IMAGE" class="img-fluid w-auto p-2" style="border-radius:30px;height: 230px;">
                  <span class=" text-white position-absolute d-flex justify-content-center align-items-center p-1" style="color:#6c6c6c;background-color: rgb(66, 218, 132);top: 23px;left: 23px;border-radius: 8px;font-size: 13px;">{{course.category.title}}</span>
                </a>
              </div>
              <div class="px-4 mb-1 w-100" dir="rtl">
                <h6 style="font-size:17px;color:#404040;">{{course.title}}</h6>
              </div>
              <div class="px-4 mb-1 w-100" dir="rtl">
                <h6 style="font-size:12px;color:#959595;">{{course.content|giyo}}</h6>
              </div>
              <div class="px-4 d-flex pb-3 justify-content-start align-items-center w-100" dir="rtl">
                <img src="{% static 'blog/images/clockblog.png' %}" alt="ICON" height="18px">
                <div style="color:#b3b3b3;font-size: 15px;" class="px-1">
                  زمان مطالعه : 
                </div>
                <div>
                  {{course.time_of_study}} دقیقه
                </div>
              </div>
            </div>
          </div>
          <!-- end card -->
        
      {% endfor %}
      
      </div> 
    </div> 
  </div>  
  <!-- end first section -->

{% endblock content %}

templates/blog/contact-us.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}
<!-- Contact Us Header -->
<div class="text-center pt-5 w-full flex justify-center px-5 pb-3 mx-5">
    <div class="flex justify-center w-full px-5 mx-5">
        <div class="border-2 border-gray-300 p-4 px-5 rounded-lg flex justify-center ml-2">
            <h1 class="text-2xl font-bold">تماس با ما 📞</h1>
        </div>
    </div>
</div>
<!-- End Contact Us Header -->

<!-- Contact Info Section -->
<div class="py-1">
    <div class="container">
        <div class="row d-flex justify-content-center" dir="rtl">
            <div class="col-12 col-md-6 d-flex flex-column align-items-center">
                <h3 class="mb-3">اطلاعات تماس</h3>
                <div class="mb-2">
                    <strong>📍 آدرس:</strong> تبریز، ایران
                </div>
                <div class="mb-2">
                    <strong>📧 ایمیل:</strong> example@email.com
                </div>
                <div class="mb-2">
                    <strong>📞 تلفن:</strong> 0123-456789
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact Info Section -->

<!-- Contact Form Section -->
<div class="py-3">
    <div class="container">
        <div class="row d-flex justify-content-center">
            
        </div>
    </div>
</div>
<!-- End Contact Form Section -->

{% endblock content %}

templates/blog/search_resualts.html
{% extends 'blog/base.html' %}






{% block content %}{% endblock content %}