accounts/urls.py
from django.urls import path 

from blog.views import review_articles,accept_article,reject_article
from .views import (
						login_view, 
						register_view,
						dashboard_view, 
                        user_dashboard_edit,
						logout_view,
						kave_negar_token_send,
                        courses_view,
                        edit_course_view,
                        create_course_view,
                        
					)

app_name= 'accounts'
urlpatterns = [

	path('login/' , login_view , name = 'login_view'),

	path('dashboard/' , dashboard_view , name = 'dashboard_view'),
    
	path('dashboard/edit/', user_dashboard_edit, name='user_dashboard_edit'),
    
	path('dashboard/courses/' , courses_view , name = 'courses_view'),
    
    path('courses/<int:course_id>/', edit_course_view, name='edit_course_view'),
    
	path('courses/create/', create_course_view, name='create_course_view'),

	path('register/' , register_view , name = 'register_view'),

	path('logout/', logout_view, name='logout_view'),

	path('kave_negar_token_send/',kave_negar_token_send,name = 'kave_negar_token_send'),
    
]

blog/urls.py
from django.urls import path,include

from .views import home_view , blog_detail,AddarticleView,SearchView,about_us,contact_us


urlpatterns = [

    path('' , home_view , name = 'blog_home'),

    path('blogs/<id>/' , blog_detail , name = 'blog_detail'),

    path('search/' , SearchView , name = 'search'),

    path('addarticle/' , AddarticleView , name = 'addarticle'),  

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

    path('about/', about_us, name='about'),

    path('contact/', contact_us, name='contact'),

 







   # path('<id>/' , comment_create , name = 'comment_create')



]

config/urls.py
from django.contrib import admin

from django.urls import path , include

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/' ,  include('accounts.urls')),

    path('' , include('blog.urls')),

    path("__reload__/", include("django_browser_reload.urls")),  # This is important!
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/User/_sidebar.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sidebar</title>
    <style>
        .sidebar {
        position: fixed;
        top: 0;
        left:-250 ; /* Initially hidden */
        width: 250px;
        height: 100vh;
        background-color: #333;
        transition: left 0.3s ease-in-out;
    }
        .sidebar.active {
            left: -250px;
        }
        @media (min-width: 320px) {
            .sidebar {
            position: fixed;
            top: 0;
            left:0 ; /* Initially hidden */
            width: 250px;
            height: 100vh;
            background-color: #333;
            transition: left 0.3s ease-in-out;
        }
        .sidebar a {
            display: flex;
            align-items: center;
            padding: 12px 18px;
            margin: 12px 0;
            border-radius: 6px;
            transition: 0.3s;
            color: white;
            text-decoration: none;
            font-size: 1.1rem;
        }
        .sidebar a:hover {
            background-color: #00d5b6;
            transform: translateX(5px);
        }
        .sidebar .icon {
            margin-left: 10px;
        }
        .sidebar .logout {
            margin-top: auto;
            text-align: center;
            padding: 12px;
            border-radius: 6px;
        }
        .sidebar .logout:hover {
            background-color: #c82333;
            transform: translateX(0);
        }
    </style>
</head>
<body>
    <div id="sidebar" class="sidebar">
    
    {% if is_admin %}
        <a href="{% url 'blog_home' %}" class="text-sm"><i class="icon">🏠</i> صفحه اصلی</a>
        <h2 class="text-center text-white font-semibold">داشبورد</h2>
        <a href="{% url 'accounts:dashboard_view' %}" class="text-sm"><i class="icon">📊</i> آمار</a>
        <a href="{% url 'accounts:courses_view' %}" class="text-sm"><i class="icon">📚</i> دوره‌ها</a>
        <a href="#" class="text-sm"><i class="icon">💬</i> کامنت ها</a>
        <a href="{% url 'accounts:user_dashboard_edit' %}" class="text-sm"><i class="icon">⚙️</i> تنظیمات</a>
        <a href="{% url 'accounts:logout_view' %}" class="logout"><i class="icon">🚪</i> خروج</a>
        </div>
    {% else %}
        <a href="{% url 'blog_home' %}" class="text-sm"><i class="icon">🏠</i> صفحه اصلی</a>
        <h2 class="text-center text-white font-semibold">داشبورد</h2>
        <a href="{% url 'accounts:dashboard_view' %}" class="text-sm"><i class="icon">📊</i> پروفایل</a>
        <a href="{% url 'accounts:courses_view' %}" class="text-sm"><i class="icon">📝</i> دوره‌های من</a>
        <a href="{% url 'accounts:user_dashboard_edit' %}" class="text-sm"><i class="icon">⚙️</i> تنظیمات</a>
        <a href="{% url 'accounts:logout_view' %}" class="logout"><i class="icon">🚪</i> خروج</a>
    </div>
    {% endif %}
    

</body>
</html>

templates/User/course_detail.html
{% load static %}
{% load tailwind_tags %}

{% tailwind_css %}
{% block content %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <link rel="icon" type="image/x-icon" href="{% static 'blog/images/logo.ico' %}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'blog/plugins/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'blog/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'blog/styles/blogs.css' %}">
    <title>ویرایش دوره</title>
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Tahoma', sans-serif;
            display: flex;
            height: 100vh;
            margin: 0;
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
            width: calc(100% - 250px);
        }

        .container {
            background: white;
            padding: 20px;
            max-width: 900px;
            margin: 40px auto;
            border-radius: 10px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            transition: 0.3s;
        }

        .btn-custom {
            background-color: #00d5b6;
            color: white;
            padding: 10px 20px;
            border-radius: 7px;
            transition: 0.3s;
            display: inline-block;
            margin-top: 20px;
            text-decoration:none;
            
        }
        .btn-custom:hover {
            background-color: #00c0a5;
        }
        .btn-red {
            background-color:rgb(213, 0, 0);
            color: white;
            padding: 10px 20px;
            border-radius: 7px;
            transition: 0.3s;
            display: inline-block;
            margin-top: 20px;
            text-decoration:none;
            
        }
        .btn-red:hover {
            background-color:rgb(119, 18, 18);
        }
        .form-input {
            width: 100%;
            padding: 12px 16px;
            margin-top: 10px;
            border-radius: 6px;
            border: 1px solid #ddd;
            font-size: 16px;
        }

        /* Hide the file input */
        #image-input {
            display: none;
        }

        /* Style for clickable image */
        .image-container {
            cursor: pointer;
            position: relative;
        }

        /* Edit icon style (initially hidden) */
        .edit-icon {
            position: absolute;
            top: 10px;
            right: 10px;
            background-color: rgba(0, 0, 0, 0.5);
            color: white;
            font-size: 18px;
            padding: 5px;
            border-radius: 50%;
            cursor: pointer;
            opacity: 0; /* Hide by default */
            transition: opacity 0.3s ease;
        }

        /* Show the edit icon on hover */
        .image-container:hover .edit-icon {
            opacity: 1; /* Show the icon */
        }

        .edit-icon:hover {
            background-color: rgba(0, 0, 0, 0.7);
        }
                /* Mobile */
@media (max-width: 768px) {
    .sidebar {
        width: 100%;
        height: 100%;
    }

    .main-content {
        margin-left: 0;
    }

    .sidebar-toggle {
        display: block !important;  /* Force show button in mobile view */
    }
}

/* Toggle button */
.sidebar-toggle {
    display: none;  /* Hide by default for desktop */
    position: absolute;
    top: 20px;
    left: 20px;
    font-size: 30px;
    cursor: pointer;
    z-index: 10;
}
    </style>
</head>

<body>
    <!-- Sidebar -->
    {% include 'User/_sidebar.html' %}

    <!-- Main Content -->
    <div class="main-content">
    <!-- Toggle Button for Mobile -->
        <button class="sidebar-toggle" id="sidebarToggle" onclick="sidebarToggle()">☰</button>
        <div class="container">
            <h1 class="text-3xl font-bold text-gray-700 mb-4">ویرایش دوره</h1>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Course Image -->
                <div class="mb-4">
                    <label for="image" class="block text-gray-700 font-semibold">تصویر دوره:</label>
                    <!-- Make the image clickable with an edit icon -->
                    <label for="image-input" class="image-container">
                        <img id="course-image" src="{% if course.image %}{{ course.image.url }}{% else %}/static/images/default-course.jpg{% endif %}" alt="{{ course.title }}" class="w-50 h-64 object-cover rounded-lg mb-4">
                        <div class="edit-icon">✏️</div>
                    </label>
                    <!-- Hidden file input field -->
                    <input type="file" name="image" id="image-input" class="form-input">
                </div>

                <!-- Course Title -->
                <div class="mb-4">
                    <label for="title" class="block text-gray-700 font-semibold">عنوان دوره</label>
                    <input type="text" name="title" id="title" value="{{ course.title }}" class="form-input" required>
                </div>

                <!-- Course content -->
                <div class="mb-4">
                    <label for="content" class="block text-gray-700 font-semibold">توضیحات دوره</label>
                    <textarea name="content" id="content" class="form-input" rows="4" required>{{ course.content }}</textarea>
                </div>
                <!-- Course Title -->
                <div class="mb-4">
                    <label for="time_of_study" class="block text-gray-700 font-semibold">مقدار زمان ساعتی دوره</label>
                    <input type="text" name="time_of_study" id="time_of_study" value="{{ course.time_of_study }}" class="form-input" required>
                </div>
                <!-- Course Title -->
                <div class="mb-4">
                    <label for="teacher" class="block text-gray-700 font-semibold">مدرس دوره</label>
                    <input type="text" name="teacher" id="teacher" value="{{ course.teacher }}" class="form-input" required>
                </div>
                <!-- Course Status -->
                <div class="mb-4">
                    <label for="status" class="block text-gray-700 font-semibold">وضعیت دوره</label>
                    <input type="checkbox" name="status" id="status" {% if course.status %}checked{% endif %}>
                    <label for="status">فعال</label>
                </div>
                <!-- Submit Button -->
                <div class="mb-4">
                    <button type="submit" class="btn-custom">ذخیره تغییرات</button>
                </div>
                

            
            </form>
            <form method="post" onsubmit="return confirm('آیا مطمئن هستید که می‌خواهید این دوره را حذف کنید؟');">
            {% csrf_token %}
                <div class="mb-4">
                    <button type="submit" name="delete_course" class="btn-red"> حذف دوره</button>
                </div>
            </form>
            <a href="{% url 'accounts:courses_view' %}" class="btn-custom">بازگشت</a>
        </div>
    </div>

    <script>
        // JavaScript to preview the selected image
        document.getElementById('image-input').addEventListener('change', function(event) {
            var reader = new FileReader();
            reader.onload = function() {
                var imageElement = document.getElementById('course-image');
                imageElement.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        });
        // Toggle Sidebar for Mobile
        function sidebarToggle() {
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('hidden');
        }
    </script>
</body>
</html>
{% endblock content %}

templates/User/courses.html
{% load static %}
{% load tailwind_tags %}
{% load django_browser_reload %}

{% tailwind_css %}
{% block content %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <link rel="icon" type="image/x-icon" href="{% static 'blog/images/logo.ico' %}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'blog/plugins/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <!-- cdn font vazir -->
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'blog/styles/main.css' %}">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'blog/styles/blogs.css' %}">
    <title>دوره‌ها</title>
    <style>
        body {
            background-color: #f8f9fa; /* Light gray */
            font-family: 'Tahoma', sans-serif;
            display: flex;
            height: 100vh;
            margin: 0;
            transition: margin-left 0.3s ease;
        }

        /* Header */
        .header {
            background-color: #ffffff;
            box-shadow: 0 3px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-bottom: 30px;
        }

        .header h1 {
            font-size: 24px;
            color: #2d3748;
            font-weight: 600;
        }

        /* Sidebar */
        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #f8f9fa;
            position: fixed;
            left: 0;
            top: 0;
            transition: transform 0.3s ease;
            transform: translateX(0);
        }

        .sidebar.hidden {
            transform: translateX(-100%);
        }
        .course-card {
            background: white;
            color:black;
            padding: 20px;
            width:300;
            border-radius: 10px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            transition: 0.3s;
            text-decoration: none; /* Remove underline from the link */
        }
        .course-card:hover {
            transform: translateY(-5px);
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
            width: calc(100% - 250px);
            transition: margin-left 0.3s ease;
        }

        .grid {
            display: grid;
            grid-template-columns: repeat(1, 1fr);
            gap: 16px;
        }
        @media (min-width: 768px) {
            .grid {
                grid-template-columns: repeat(3, 1fr);
            }
        }

        /* Mobile */
@media (max-width: 768px) {
    .sidebar {
        width: 100%;
        height: 100%;
    }

    .main-content {
        margin-left: 0;
    }

    .sidebar-toggle {
        display: block !important;  /* Force show button in mobile view */
    }
}

/* Toggle button */
.sidebar-toggle {
    display: none;  /* Hide by default for desktop */
    position: absolute;
    top: 20px;
    left: 20px;
    font-size: 30px;
    cursor: pointer;
    z-index: 10;
}

    </style>
</head>

<body>

    <!-- Sidebar -->
    <div class="sidebar" id="sidebar">
        {% include 'User/_sidebar.html' %}
    </div>

    <!-- Main Content -->
    <div class="main-content">
        <!-- Toggle Button for Mobile -->
         <button class="sidebar-toggle" id="sidebarToggle" onclick="sidebarToggle()">☰</button>

        <!-- Header -->
        <div class="header py-4 px-6 bg-white shadow-lg">
            <h1 class="text-xl font-semibold text-gray-700">دوره‌ها</h1>
        </div>
    
        <!-- Search Bar -->
        <div class="mt-4 ">
        <input type="text" class="search-bar mx-2 mt-2" placeholder="جستجو در دوره‌ها 🔍 ">
        <a class="btn btn-primary position-absolute px-2" href="{% url 'accounts:create_course_view' %}">افزودن دوره +</a>
        </div>

        <!-- Courses -->
        <div class="grid mt-3 px-4">
            {% if courses %}
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                    {% for course in courses %}
                    <a href="{% url 'accounts:edit_course_view' course.id %}" class="course-card"> 
                        <h3 class="font-semibold text-xl">{{ course.title|slice:":30" }}</h3>
                        <img src="{{ course.image.url }}" alt="Default Image" class=" w-100 h-48 object-cover rounded-lg">
                        <p class="text-gray-600 mt-2">{{ course.content|slice:":50" }}...</p>
                     </a>
                    {% endfor %}
                </div>
            {% else %}
            <p class="text-center text-gray-700 mt-5">هیچ دوره‌ای برای نمایش وجود ندارد.</p>
            {% endif %}
        </div>
    </div>

    <script>
        // Toggle Sidebar for Mobile
        function sidebarToggle() {
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('hidden');
        }
    </script>
</body>
</html>

{% endblock content %}

templates/User/create_course.html
{% load static %}
{% load tailwind_tags %}

{% tailwind_css %}
{% block content %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <link rel="icon" type="image/x-icon" href="{% static 'blog/images/logo.ico' %}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'blog/plugins/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'blog/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'blog/styles/blogs.css' %}">
    <title>ویرایش دوره</title>
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Tahoma', sans-serif;
            display: flex;
            height: 100vh;
            margin: 0;
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
            width: calc(100% - 250px);
        }

        .container {
            background: white;
            padding: 20px;
            max-width: 900px;
            margin: 40px auto;
            border-radius: 10px;
            box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
            transition: 0.3s;
        }

        .btn-custom {
            background-color: #00d5b6;
            color: white;
            padding: 10px 20px;
            border-radius: 7px;
            transition: 0.3s;
            display: inline-block;
            margin-top: 20px;
            text-decoration:none;
            
        }
        .btn-custom:hover {
            background-color: #00c0a5;
        }

        .form-input {
            width: 100%;
            padding: 12px 16px;
            margin-top: 10px;
            border-radius: 6px;
            border: 1px solid #ddd;
            font-size: 16px;
        }

        /* Hide the file input */
        #image-input {
            display: none;
        }

        /* Style for clickable image */
        .image-container {
            cursor: pointer;
            position: relative;
        }

        /* Edit icon style (initially hidden) */
        .edit-icon {
            position: absolute;
            top: 10px;
            right: 10px;
            background-color: rgba(0, 0, 0, 0.5);
            color: white;
            font-size: 18px;
            padding: 5px;
            border-radius: 50%;
            cursor: pointer;
            opacity: 0; /* Hide by default */
            transition: opacity 0.3s ease;
        }

        /* Show the edit icon on hover */
        .image-container:hover .edit-icon {
            opacity: 1; /* Show the icon */
        }

        .edit-icon:hover {
            background-color: rgba(0, 0, 0, 0.7);
        }
                /* Mobile */
@media (max-width: 768px) {
    .sidebar {
        width: 100%;
        height: 100%;
    }

    .main-content {
        margin-left: 0;
    }

    .sidebar-toggle {
        display: block !important;  /* Force show button in mobile view */
    }
}

/* Toggle button */
.sidebar-toggle {
    display: none;  /* Hide by default for desktop */
    position: absolute;
    top: 20px;
    left: 20px;
    font-size: 30px;
    cursor: pointer;
    z-index: 10;
}
    </style>
</head>

<body>
    <!-- Sidebar -->
    {% include 'User/_sidebar.html' %}

    <!-- Main Content -->
    <div class="main-content">
    <!-- Toggle Button for Mobile -->
        <button class="sidebar-toggle" id="sidebarToggle" onclick="sidebarToggle()">☰</button>
        <div class="container">
            <h1 class="text-3xl font-bold text-gray-700 mb-4">ویرایش دوره</h1>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Course Image -->
                <div class="mb-3 ">
                    <label for="image" class="block text-gray-700 font-semibold">تصویر دوره:</label>
                    <!-- Make the image clickable with an edit icon -->
                    <label for="image-input" class="image-container">
                        <img id="course-image" src="{% static 'blog/images/add-image-photo-icon.png' %}" class="w-50 h-64 object-cover rounded-lg mb-4">
                        <div class="edit-icon">✏️</div>
                    </label>
                    <!-- Hidden file input field -->
                    <input type="file" name="image" id="image-input" class="form-input">
                </div>

                <!-- Course Title -->
        <div class="mb-4">
            <label for="title" class="block text-gray-700 font-semibold">عنوان دوره</label>
            <input type="text" name="title" id="title" class="form-input" placeholder="مثال: دوره آموزش جنگو" required>
        </div>

        <!-- Course content -->
        <div class="mb-4">
            <label for="content" class="block text-gray-700 font-semibold">توضیحات دوره</label>
            <textarea name="content" id="content" class="form-input" rows="4" placeholder="مثال: در این دوره با مفاهیم پایه جنگو آشنا خواهید شد." required>{{ course.content }}</textarea>
        </div>

        <!-- Course Time -->
        <div class="mb-4">
            <label for="time_of_study" class="block text-gray-700 font-semibold">مقدار زمان ساعتی دوره</label>
            <input type="text" name="time_of_study" id="time_of_study" value="{{ course.time_of_study }}" class="form-input" placeholder="مثال: 40 " required>
        </div>

        <!-- Course Teacher -->
        <div class="mb-4">
            <label for="teacher" class="block text-gray-700 font-semibold">مدرس دوره</label>
            <input type="text" name="teacher" id="teacher" value="{{ course.teacher }}" class="form-input" placeholder="مثال: علی رضایی" required>
        </div>

        <div class="mb-4">
            <label for="price" class="block text-gray-700 font-semibold">قیمت دوره</label>
            <input type="text" name="price" id="price" value="{{ course.price }}" class="form-input" placeholder="مثال:50000" required>
        </div>

                <!-- Submit Button -->
                <div class="mb-4">
                    <button type="submit" class="btn-custom">ذخیره تغییرات</button>
                </div>
            </form>

            <a href="{% url 'accounts:courses_view' %}" class="btn-custom">بازگشت</a>
        </div>
    </div>

    <script>
        // JavaScript to preview the selected image
        document.getElementById('image-input').addEventListener('change', function(event) {
            var reader = new FileReader();
            reader.onload = function() {
                var imageElement = document.getElementById('course-image');
                imageElement.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        });
        // Toggle Sidebar for Mobile
        function sidebarToggle() {
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.toggle('hidden');
        }
    </script>
</body>
</html>
{% endblock content %}